import type { Product, Category } from "@/types/product";

export const localCategories: Category[] = [
  { id: "cat-1", nama: "Papan Nama", slug: "papan-nama", urutan: 1, gambar: "/images/products/papan-nama.jpg", deskripsi: "Papan nama toko dan kantor dengan material premium" },
  { id: "cat-2", nama: "Neon Box", slug: "neon-box", urutan: 2, gambar: "/images/products/neon-box.jpg", deskripsi: "Neon box backlit LED untuk signage 24 jam" },
  { id: "cat-3", nama: "Rambu-Rambu", slug: "rambu-rambu", urutan: 3, gambar: "/images/products/rambu.jpg", deskripsi: "Rambu signage dan petunjuk arah" },
  { id: "cat-4", nama: "Huruf Timbul", slug: "huruf-timbul", urutan: 4, gambar: "/images/products/huruf-timbul.jpg", deskripsi: "Huruf timbul 3D akrilik, stainless, galvanis" },
  { id: "cat-5", nama: "Totem & Pylon", slug: "totem-pylon", urutan: 5, gambar: "/images/products/totem-pylon.jpg", deskripsi: "Totem dan pylon sign berdiri bebas" },
  { id: "cat-6", nama: "Sticker Branding Mobil", slug: "sticker-branding-mobil", urutan: 6, gambar: "/images/products/sticker-mobil.jpg", deskripsi: "Full body sticker branding kendaraan" },
  { id: "cat-7", nama: "Sticker Sandblast Kaca", slug: "sticker-sandblast-kaca", urutan: 7, gambar: "/images/products/sticker-sandblast.jpg", deskripsi: "Sticker sandblast untuk kaca gedung dan toko" },
  { id: "cat-8", nama: "Sticker Cutting", slug: "sticker-cutting", urutan: 8, gambar: "/images/products/sticker-cutting.jpg", deskripsi: "Cutting sticker custom untuk branding" },
  { id: "cat-9", nama: "Event Booth", slug: "event-booth", urutan: 9, gambar: "/images/products/event-booth.jpg", deskripsi: "Booth pameran dan event custom" },
  { id: "cat-10", nama: "E Kiosk & Charger Point", slug: "e-kiosk-charger-point", urutan: 10, gambar: "/images/products/e-kiosk.jpg", deskripsi: "Kiosk interaktif dan charging station" },
  { id: "cat-11", nama: "Electric POP Display", slug: "electric-pop-display", urutan: 11, gambar: "/images/products/electric-pop.jpg", deskripsi: "Display Point of Purchase elektrik" },
];

export const localProducts: Product[] = [
  {
    id: "prod-1",
    nama: "Papan Nama Akrilik Custom",
    slug: "papan-nama-akrilik-custom",
    category_id: "cat-1",
    category_nama: "Papan Nama",
    deskripsi_singkat: "Papan nama toko dari akrilik tebal 3-10mm dengan cutting laser presisi dan pilihan warna lengkap.",
    deskripsi_lengkap: "Papan nama akrilik custom adalah pilihan utama untuk toko, klinik, kantor, dan berbagai bisnis lainnya. Terbuat dari lembaran akrilik berkualitas tinggi dengan ketebalan 3mm hingga 10mm, dipotong menggunakan laser presisi untuk hasil yang rapi dan elegan.\n\nTersedia dalam berbagai pilihan warna: bening, putih, hitam, merah, biru, emerald, dan gold mirror. Bisa ditambahkan backdrop kayu, aluminium, atau stainless steel sesuai keinginan.\n\nSpesifikasi:\n- Material: Akrilik进口 3-10mm\n- Finishing: Cutting laser, UV printing, atau letter timbul\n- Ukuran: Custom sesuai kebutuhan\n- Include: Desain gratis + pemasangan",
    harga: 150000,
    satuan: "Unit",
    gambar: ["/images/products/papan-nama.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-15T08:00:00.000Z",
    diupdate_pada: "2026-01-15T08:00:00.000Z",
  },
  {
    id: "prod-2",
    nama: "Neon Box Single Side LED",
    slug: "neon-box-single-side-led",
    category_id: "cat-2",
    category_nama: "Neon Box",
    deskripsi_singkat: "Neon box satu sisi dengan rangka aluminium dan lampu LED hemat energi, terlihat jelas siang dan malam.",
    deskripsi_lengkap: "Neon box single side adalah solusi signage paling populer untuk toko di pinggir jalan. Rangka aluminium kokoh dengan panel flexy banner atau akrilik transparan, dilengkapi lampu LED hemat energi yang menerangi logo dan nama bisnis Anda.\n\nKeunggulan neon box kami:\n- Rangka aluminium anti karat\n- LED hemisphere brand terpercaya, hemat listrik\n- Banner flexy indoor/outdoor grade\n- Tahan cuaca hujan dan panas\n- Garansi 1 tahun\n\nSpesifikasi:\n- Rangka: Aluminium box section\n- Panel: Flexy banner 440gsm atau akrilik\n- Lampu: LED T5/T8 hemisphere\n- Ukuran: Custom (min 60x60cm)\n- Daya: 20-80 watt tergantung ukuran",
    harga: 200000,
    satuan: "Unit",
    gambar: ["/images/products/neon-box.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-16T08:00:00.000Z",
    diupdate_pada: "2026-01-16T08:00:00.000Z",
  },
  {
    id: "prod-3",
    nama: "Rambu Signage Custom",
    slug: "rambu-signage-custom",
    category_id: "cat-3",
    category_nama: "Rambu-Rambu",
    deskripsi_singkat: "Rambu signage petunjuk arah dan informasi dari aluminium composite panel (ACP) tahan cuaca.",
    deskripsi_lengkap: "Rambu signage custom untuk petunjuk arah, informasi fasilitas, dan branding area. Terbuat dari Aluminium Composite Panel (ACP) 4mm yang ringan namun kokoh, dengan printing UV resolusi tinggi yang tahan outdoor.\n\nCocok untuk:\n- Petunjuk arah parkir\n- Rambu gedung dan lantai\n- Signage restoran dan cafe\n- Rambu pertunjukan dan event\n\nSpesifikasi:\n- Material: ACP 4mm (Seven, Alucobond, atau equivalent)\n- Finishing: UV printing full color + laminasi\n- Rangka: Aluminium hollow\n- Ukuran: Custom\n- Daya tahan: 5-7 tahun outdoor",
    harga: 150000,
    satuan: "Rambu",
    gambar: ["/images/products/rambu.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-17T08:00:00.000Z",
    diupdate_pada: "2026-01-17T08:00:00.000Z",
  },
  {
    id: "prod-4",
    nama: "Huruf Timbul Stainless Steel",
    slug: "huruf-timbul-stainless-steel",
    category_id: "cat-4",
    category_nama: "Huruf Timbul",
    deskripsi_singkat: "Huruf timbul 3D dari stainless steel mirror atau brushed, welding presisi, tampilan premium.",
    deskripsi_lengkap: "Huruf timbul stainless steel adalah pilihan paling premium untuk signage bisnis Anda. Dibuat dari lembaran stainless steel asli dengan ketebalan 0.8mm-1.2mm, dibentuk menggunakan mesin CNC presisi dan welding rapi.\n\nTersedia dalam finishing:\n- Mirror (mengkilap seperti cermin)\n- Brushed (tekstur garis halus)\n- Hitam doff\n- Gold mirror\n\nFitur:\n- Bisa ditambahkan lampu LED backlit\n- Anti karat dan tahan cuaca\n- Ketebalan huruf: 3-10cm\n- Include tiang penyangga atau mounting bracket\n- Garansi finishing 3 tahun",
    harga: 80000,
    satuan: "Huruf",
    gambar: ["/images/products/huruf-timbul.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-18T08:00:00.000Z",
    diupdate_pada: "2026-01-18T08:00:00.000Z",
  },
  {
    id: "prod-5",
    nama: "Totem Sign Galaxy Run",
    slug: "totem-sign-galaxy-run",
    category_id: "cat-5",
    category_nama: "Totem & Pylon",
    deskripsi_singkat: "Totem sign berdiri bebas tinggi 2-4 meter, rangka galvanis, panel akrilik backlit LED.",
    deskripsi_lengkap: "Totem sign adalah signage berdiri bebas yang diletakkan di depan gedung atau area strategis. Cocok untuk mal, SPBU, restoran cepat saji, dan area komersial besar.\n\nSpesifikasi:\n- Tinggi: 2-4 meter (custom)\n- Rangka: Galvanis + cat duco automotive\n- Panel: Akrilik transparan + sticker ONYX\n- Lampu: LED backlit hemisphere\n- Fondasi: Beton bertulang\n\nInclude:\n- Survei lokasi\n- Desain 3D\n- Izin pemasangan (jika diperlukan)\n- Pemasangan oleh tim profesional\n- Garansi struktur 5 tahun",
    harga: 1300000,
    satuan: "Unit",
    gambar: ["/images/products/totem-pylon.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-19T08:00:00.000Z",
    diupdate_pada: "2026-01-19T08:00:00.000Z",
  },
  {
    id: "prod-6",
    nama: "Full Body Sticker Branding Mobil",
    slug: "full-body-sticker-branding-mobil",
    category_id: "cat-6",
    category_nama: "Sticker Branding Mobil",
    deskripsi_singkat: "Branding mobil full body dengan sticker premium Oracal 651, printing eco-solvent resolusi tinggi.",
    deskripsi_lengkap: "Sticker branding mobil full body adalah iklan berjalan yang paling efektif. Kami menggunakan material sticker premium Oracal 651 atau equivalent dengan printing eco-solvent resolusi tinggi 1440dpi.\n\nKeunggulan:\n- Sticker Oracal 651 grade automotive\n- Printing eco-solvent resolusi 1440dpi\n- Laminasi glossy/matte untuk perlindungan UV\n- Pemasangan tanpa gelembung udara\n- Bisa dilepas tanpa merusak cat\n- Daya tahan 3-5 tahun outdoor\n\nInclude:\n- Desain grafis\n- Pemasangan oleh teknisi ahli\n- Survei ukuran kendaraan\n- Garansi 1 tahun",
    harga: 1000000,
    satuan: "Mobil",
    gambar: ["/images/products/sticker-mobil.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-20T08:00:00.000Z",
    diupdate_pada: "2026-01-20T08:00:00.000Z",
  },
  {
    id: "prod-7",
    nama: "Sticker Sandblast Kaca",
    slug: "sticker-sandblast-kaca",
    category_id: "cat-7",
    category_nama: "Sticker Sandblast Kaca",
    deskripsi_singkat: "Sticker sandblast efek es untuk kaca toko dan gedung, memberikan privasi tetapi tetap tembus cahaya.",
    deskripsi_lengkap: "Sticker sandblast memberikan efek kaca es yang elegan pada kaca toko, kantor, atau gedung. Memberikan privasi tanpa menghalangi cahaya masuk.\n\nJenis:\n- Sandblast polos (frosted)\n- Sandblast motif (custom pattern)\n- Sandblast logo/teks (cutting)\n\nKeunggulan:\n- Memberikan efek privasi\n- Tetap tembus cahaya (40-60%)\n- Anti UV\n- Bisa dipasang full atau partial\n- Mudah dibersihkan\n\nUkuran standar: 122 x 50 cm per lembar\nHarga: Rp 25.000/lembar",
    harga: 25000,
    satuan: "Lembar (122x50cm)",
    gambar: ["/images/products/sticker-sandblast.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-21T08:00:00.000Z",
    diupdate_pada: "2026-01-21T08:00:00.000Z",
  },
  {
    id: "prod-8",
    nama: "Sticker Cutting Custom",
    slug: "sticker-cutting-custom",
    category_id: "cat-8",
    category_nama: "Sticker Cutting",
    deskripsi_singkat: "Cutting sticker custom dari bahan Oracal, tersedia berbagai warna, cocok untuk branding dan dekorasi.",
    deskripsi_lengkap: "Sticker cutting custom adalah solusi branding yang fleksibel dan ekonomis. Dipotong menggunakan mesin cutting plotter presisi dari bahan sticker Oracal premium.\n\nCocok untuk:\n- Nama toko dan logo\n- Jam buka dan informasi\n- Dekorasi dinding dan kaca\n- Branding kendaraan\n- Label dan identitas produk\n\nMaterial:\n- Oracal 651 (outdoor 3-5 tahun)\n- Oracal 638 (indoor)\n- Chameleon (gradient color)\n- Blackboard (papan tulis)\n- Whiteboard\n\nHarga mulai Rp 2.000/cm²",
    harga: 2000,
    satuan: "Sticker",
    gambar: ["/images/products/sticker-cutting.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-22T08:00:00.000Z",
    diupdate_pada: "2026-01-22T08:00:00.000Z",
  },
  {
    id: "prod-9",
    nama: "Event Booth Custom",
    slug: "event-booth-custom",
    category_id: "cat-9",
    category_nama: "Event Booth",
    deskripsi_singkat: "Booth pameran dan event custom dari aluminium, acrylic, dan kayu. Include desain, produksi, dan instalasi.",
    deskripsi_lengkap: "Kami menyediakan jasa pembuatan booth event dan pameran secara custom. Dari desain 3D hingga pemasangan di lokasi, semuanya dikerjakan oleh tim profesional.\n\nJenis booth:\n- Booth portable (ringkas, mudah dipindah)\n- Booth semi-permanent\n- Booth permanent (untuk mal dan exhibition center)\n\nMaterial:\n- Rangka: Aluminium / besi hollow\n- Panel: Melamin, HPL, akrilik\n- Backdrop: Printing flexi / canvas\n- Counter: Akrilik / kayu\n\nInclude:\n- Desain 3D\n- Produksi\n- Transportasi\n- Instalasi di lokasi\n- Bongkar pasca event",
    harga: 25000000,
    satuan: "Unit",
    gambar: ["/images/products/event-booth.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-23T08:00:00.000Z",
    diupdate_pada: "2026-01-23T08:00:00.000Z",
  },
  {
    id: "prod-10",
    nama: "E Kiosk & Charger Point",
    slug: "e-kiosk-charger-point",
    category_id: "cat-10",
    category_nama: "E Kiosk & Charger Point",
    deskripsi_singkat: "Kiosk digital interaktif dan charging station untuk mall, gedung, dan area publik.",
    deskripsi_lengkap: "E Kiosk dan Charger Point adalah solusi digital signage interaktif untuk gedung, mall, dan area publik. Kami menyediakan desain, fabrikasi, dan instalasi kiosk digital custom.\n\nFitur:\n- Layar touchscreen 21-42 inch\n- Charging port USB-A dan USB-C\n- Branded enclosure custom\n- Software interaktif (opsional)\n- Monitoring penggunaan (opsional)\n\nCocok untuk:\n- Mall dan pusat perbelanjaan\n- Gedung perkantoran\n- Bandara dan stasiun\n- Hotel dan resort\n- Area rekreasi",
    harga: 8000000,
    satuan: "Unit",
    gambar: ["/images/products/e-kiosk.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-24T08:00:00.000Z",
    diupdate_pada: "2026-01-24T08:00:00.000Z",
  },
  {
    id: "prod-11",
    nama: "Electric POP Display",
    slug: "electric-pop-display",
    category_id: "cat-11",
    category_nama: "Electric POP Display",
    deskripsi_singkat: "Display Point of Purchase elektrik dengan lampu LED dan moving mechanism untuk menarik perhatian pelanggan.",
    deskripsi_lengkap: "Electric POP Display adalah display Point of Purchase yang dilengkapi penerangan LED dan mekanisme bergerak untuk menarik perhatian pelanggan di area kasir atau entrance toko.\n\nFitur:\n- Penerangan LED backlight\n- Moving mechanism (rotating / sliding)\n- Branded enclosure custom\n- Remote control (opsional)\n- Timer on/off (opsional)\n\nCocok untuk:\n- Retail dan minimarket\n- Restoran dan cafe\n- Showroom mobil\n- Area kasir dan checkout",
    harga: 2500000,
    satuan: "Unit",
    gambar: ["/images/products/electric-pop.jpg"],
    status: "aktif",
    dibuat_pada: "2026-01-25T08:00:00.000Z",
    diupdate_pada: "2026-01-25T08:00:00.000Z",
  },
];

export function getLocalProducts(categorySlug?: string): Product[] {
  if (categorySlug) {
    const cat = localCategories.find((c) => c.slug === categorySlug);
    if (!cat) return [];
    return localProducts.filter((p) => p.category_id === cat.id && p.status === "aktif");
  }
  return localProducts.filter((p) => p.status === "aktif");
}

export function getLocalProductBySlug(slug: string): Product | undefined {
  return localProducts.find((p) => p.slug === slug);
}

export function getLocalCategoryBySlug(slug: string): Category | undefined {
  return localCategories.find((c) => c.slug === slug);
}
